from django.urls import path
from .views import *


urlpatterns = [
    path('product/list/', product_list),
    path('product/list/insert/', product_insert),
    path('product/list/<str:pk>', product_search),
    path('product/list/<int:pk>/', product_detail),
    # path('product/list/<int:pk>/edit_inventory/', product_update),
    # path('customer/register/', )
    # DO NOT EDIT this file, go to market/urls.py
]
