from django.urls import path
from knox import views as knox_views
from .views import *


urlpatterns = [
    path('product/list/', product_list),
    path('product/insert/', product_insert),
    path('product/list/<str:pk>', product_search),
    path('product/list/<int:pk>/', product_detail),
    path('product/list/<int:pk>/edit_inventory/', product_update),
    path('customer/register/', RegisterAPI.as_view(), name='register'),
    path('customer/login/', LoginAPI.as_view(), name='login'),
    path('customer/list/', LoginAPI.as_view(), name='list'),
    path('customer/logout/', knox_views.LogoutView.as_view(), name='logout'),
    # DO NOT EDIT this file, go to market/urls.py
]
