from django.urls import path
from .views import product_list, product_detail, product_update

urlpatterns = [
    path('product/list/', product_list),
    path('product/list/<int:pk>/', product_detail),
    path('product/list/<int:pk>/edit_inventory/', product_update),
    # DO NOT EDIT this file, go to market/urls.py

]
